export const GET_TAKEAWAY_DATA = 'GET_TAKEAWAY_DATA';
export const DELETE_TAKEAWAY_DATA = 'DELETE_TAKEAWAY_DATA';
export const TAKEAWAY_DATA_RETURNED = 'TAKEAWAY_DATA_RETURNED';
export const TAKEAWAY_DATA_ERROR = 'TAKEAWAY_DATA_ERROR';