export const TAKEAWAY_DATA_REQUEST = 'TAKEAWAY_DATA_REQUEST';
export const TAKEAWAY_DATA_RECEIVED = 'TAKEAWAY_DATA_RECEIVED';
export const TAKEAWAY_DATA_ERROR = 'TAKEAWAY_DATA_ERROR'; 

export const TAKEAWAY_DELETE_REQUEST = 'TAKEAWAY_DELETE_REQUEST';
export const TAKEAWAY_DELETE_SUCCESS = 'TAKEAWAY_DELETE_SUCCESS';
export const TAKEAWAY_DELETE_ERROR = 'TAKEAWAY_DELETE_ERROR';
